### ISSUE TITLE
Connecting the two nodes via router.

### ISSUE THREAD

**Issue by asheeshtripathi** [alfredtso/ns-3-project#1]
Hi, I wanted to simulate two CSMA nodes that are connected to each other via a router/some other mechanism.

**Comment by alfredtso** [comment]
> Hi, I wanted to simulate two CSMA nodes that are connected to each other via a router/some other mechanism. 

Hi, it has been long since i last touched this, but i m sure i have came across the situation you mentioned in one of the example provided in the example folders in the ns3 official project source code. Can you try to have a look ?

**Comment by asheeshtripathi** [comment]
Thanks for your reply. I found some examples in ns3 examples.
